### ISSUE TITLE
Easy Deploy on Linux like Windows

### ISSUE THREAD

**Issue by ghost** [d-s-x/bomi#13]
Hi BOMI Media Player is an Amazing App but its a bit hard to compile and distribute it to all Major Linux Distros , So Why don't we ease everything up for the developers and users.

AppImage is a cool tool that creates standalone executables for linux that are self-contained , if we deploy qt shared library with bomi complied and wrap it up with AppImage , Any Linux user can just use bomi with a single click , and we can also create a gui installer with Qt Installer Framework.

Please go through this pages,

https://github.com/AppImage/AppImageKit - AppImage
http://doc.qt.io/qt-5/deployment.html - Qt Deploy using Qt Shared Libs ( No Static Required )
https://doc.qt.io/qtinstallerframework/index.html - Qt Installer Framework 

By using these , Linux users just have to download and open , no need for root access or to maintain .rpm or .deb files!

Whats on your mind , I would be happy to work on this !

**Comment by d-s-x** [comment]
> BOMI [...] a bit hard to compile

Yeah. `./configure && make` is so hard :wink: 

> Why don't we ease everything up for the developers and users.

Me? I don't have time for this but contributions are welcome.

> By using these , Linux users just have to download and open , no need for root access or to maintain .rpm or .deb files!

Honestly, this is illogical. rpm and deb files are maintained automatically (with package manager). How do you maintain whatever you've downloaded manually? Probably manually.

> Whats on your mind , I would be happy to work on this !

I'd rather spend my time on porting bomi to latest mpv. You are free to implement whatever you want though. I'll merge it as long as it doesn't break existing build system.

**Comment by ghost** [comment]
okay got it.

**Comment by probonopd** [comment]
> Yeah. ./configure && make is so hard :wink:

Sorry but exactly this attitude is what kills "Desktop Linux" for "normal people".

> Honestly, this is illogical. rpm and deb files are maintained automatically (with package manager). 

Only that the matest version probably is not in the distribution. Anyways not in an LTS one.

> How do you maintain whatever you've downloaded manually? Probably manually.

Exactly as the title says, "like Windows". The user can download a file from the project's download file.

Additionally, check out AppImageUpdate.

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by d-s-x** [comment]
@probonopd,
I'd like to put emphasis on following phrase: "I don't have time for this but contributions are welcome."

I'm not against AppImage, Flatpak and/or statically linked binaries.
If anyone is going to implement it I'll gladly merge it.
