### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by Djaler** [d-s-x/bomi#16]
What about packaging? Like a deb or snap?

**Comment by d-s-x** [comment]
There is a debian folder with a shell script for debuild. I guess it can build the deb.
Also there is a PKGBUILD for arch and an rpm spec.

No snap yet though. Pull requests are welcome :wink:

**Comment by Djaler** [comment]
Now ppa-repository exists https://launchpad.net/~nemonein/+archive/ubuntu/tailored
