### ISSUE TITLE
New Simple and Elegant Installer for  All Linux Distros and Windows Too.. 

### ISSUE THREAD

**Issue by ghost** [d-s-x/bomi#7]
Bomi is such a Beautiful and Powerful Player , but it is Hard to install on some distro , And there are no support on this topic anywhere. So My Idea is that , We Static Compile the Whole BOMI Player and Make a Static Compiled Qt Based Setup for Specific Architectures  for Every Linux Distros(i.e Two Setup files , 1. Linux x86_x64 and 2. Linux x86). This Way , The Users just have to download the setup file and just install.(Just like LokiSetup) 

For Example , Take a Look at the qt offline setup for Linux.

**Comment by d-s-x** [comment]
@deathsec,

> Qt Based Setup
> The Users just have to download the setup file and just install.
> LokiSetup

I'm not familiar with that technology. Are you talking about flatpak/snappy/etc. or "Qt based setup" is something different?

> bomi is Hard to install on some distro

I truly believe that every piece of software should be installed via package managers. If some distro doesn't have bomi package already that means that the distro have small user base and each user of such distro should know how to package software manually.

> So My Idea is that , We Static Compile [...]

You are welcome to create a pull request with something like `static/build.sh`. I won't maintain it though. Also, this is not official repo so there is no point in the first place.

**Comment by ghost** [comment]
>  I'm not familiar with that technology. Are you talking about flatpak/snappy/etc. or "Qt based setup" is   
> something different?   

Snappy/flatpak is not what I mentioned( Snappy is so sloppy! ). This is Kind of old but hard to do but very rewarding!

Let Me Give you examples...   

# Electron by Github

Electron used to create cross platform programs with HTML/CSS/JS and NodeJS for Backend.   
If a Program is Developed in Electron it outputs some files with a executable for Linux/Windows/MacOSX   
Only the Developer compiles the program and the executable is given to the user.   
And the user (i.e Linux/Windows/MacOSX) just Have to execute the program and just start using it.    
Even Linux Users don't have to compile anything , it just runs without any dependencies!.   
**This is Only Possible by Static Compiling... (You Know Already , right ?)**

If you are still unclear. Download this tar -> [https://github.com/exercism/gui/releases/download/v0.4.2/exercism-gui-linux-x64-v0.4.2.tar.gz](https://github.com/exercism/gui/releases/download/v0.4.2/exercism-gui-linux-x64-v0.4.2.tar.gz)

### To Install and Run
`
 $ tar -xvf exercism-gui-linux-x64-v0.4.2.tar.gz  ; cd exercism-gui-linux-x64 ; ./exercism-gui
`

If you inspect the files , you can see that electron itself is statically compiled thus can run on any linux    
wiithout any dependencies. **So Imagine this to BOMI , it will be lot easier for users to get BOMI**

**Comment by d-s-x** [comment]
@deathsec,

> Developer compiles the program and the executable is given to the user
> the user just Have to execute the program and just start using it.
> This is Only Possible by Static Compiling...

This is also possible with flatpak-like packaging. I don't want to reinvent the wheel.

> So Imagine this to BOMI , it will be lot easier for users to get BOMI

How this is easier than `yaourt -S bomi` or `apt install bomi`?

**Comment by ghost** [comment]
I Suppose , I Should Fork!.
Good Day.
Thank You for your Time.. 
[ How can apt , yaourt or pacman can install bomi to 1000+ Linux Distro's ? Without Compiling from Source.]
